# YAML for setting up a conda environment for
# the netmonitor library
name: netmonitor
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - matplotlib
  - netaddr
  - pandas
  - pip
  - pyfiglet
  - pylint
  - pytest
  - psutil
  - python>=3.9
  - scapy
  - schedule
  - pip:
      - urllib3