# YAML for setting up a conda environment for
# the netmonitor library
name: netmonitor
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - pip
  - pylint
  - pytest
  - psutil
  - python>=3.9
  - scapy
  - pygobject
  - gtk3